### ISSUE TITLE
Sample code for theme screenshots

### ISSUE THREAD

**Issue by TBuryanek** [lucattelli/ab4-themes#2]
Should we create some sample code to use for theme screenshots? :-)
To show different parts of codes:
- keywords, comments, operators, hardcoded values...

**Comment by alexey-arseniev** [comment]
Hi Thomas,

there is already one in the "test" folder =>
https://github.com/lucattelli/ab4-themes/blob/master/test/abap_test.abap

But probably we can minimize it in a way, that one can demonstrate all
highlighting variations in small line count.
If you have better example, or you have recommendation of how to update one
I mentioned, share it with us ;)

BR, Alexey.

2017-08-04 8:50 GMT+02:00 Tomas <notifications@github.com>:

**Comment by TBuryanek** [comment]
Created sample file #3

**Comment by alexey-arseniev** [comment]
Approved and extended a little bit
