### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by BardoBravo** [lucattelli/ab4-themes#4]
Hi,

After imporint the file abap_spec.xml into my ABAP Editor folder, the error 'DTD is prohibited.' is raised in window 'LoadXML Malformed XML Error', and the system crashes.

Any idea on how to solve it?

[]s

**Comment by TBuryanek** [comment]
I think that abap_spec.xml files are SAP Logon / SAP GUI version dependable (also probably version of SW components).

So proper way would be compare original and new file in text mode and copy only the sections of XML which are setting colors... if there are lot of other differences.

**Comment by alexey-arseniev** [comment]
Hi @BardoBravo ,

which schema file you have imported?  Actually, the error already giving an explanation - the XML is malformed. So, probably the file was edited by you and there is some unclosed XML tag or whatever. Try to check the file in any online XML validator. 
For example, try this one: http://www.xmlvalidation.com/ 
Another possible reason that schema file contains a reference to XML validation file, which is not available (but I do not see that in current file).

BR,
Alexey

**Comment by BardoBravo** [comment]
Hi,
A colleague of mine sent me the file he used and it worked.
Not sure what happenned with the original file.
Hugs
